#!/bin/bash

# Simple deployment script for Phala CVM
echo "================================================"
echo "   Akavelink Phala CVM Deployment Helper       "
echo "================================================"
echo ""
echo "Docker Image: dylanckawalec/akavelink:latest"
echo "Version: v2.0"
echo ""
echo "Your CVM ID: 0caa6fa774ccca678586fb1d142ccc627a2f96c1"
echo "Current URL: https://0caa6fa774ccca678586fb1d142ccc627a2f96c1-80.dstack-prod5.phala.network"
echo ""
echo "To update your Phala CVM with the latest image:"
echo ""
echo "Option 1: Via Phala Dashboard (Recommended)"
echo "-------------------------------------------"
echo "1. Go to: https://dashboard.phala.network/dstack"
echo "2. Find your CVM: 0caa6fa774ccca678586fb1d142ccc627a2f96c1"
echo "3. Click 'Restart' or 'Redeploy' to pull the latest image"
echo ""
echo "Option 2: Via Phala CLI"
echo "------------------------"
echo "export PHALA_CLOUD_API_KEY='your-api-key'"
echo "phala auth login \$PHALA_CLOUD_API_KEY"
echo "phala cvms restart 0caa6fa774ccca678586fb1d142ccc627a2f96c1"
echo ""
echo "Latest Updates in v2.0:"
echo "• Upload progress bar with real-time tracking"
echo "• List Objects button for file browsing"
echo "• Clickable download links throughout UI"
echo "• API reference moved to bottom"
echo "• Cleaner UI without redundant elements"
echo ""
echo "================================================"
