#!/bin/bash

echo "========================================"
echo "   UPDATE PHALA CVM TO v2.0            "
echo "========================================"
echo ""
echo "CVM Status Check:"
echo "-----------------"

# Check current deployment
URL="https://0caa6fa774ccca678586fb1d142ccc627a2f96c1-80.dstack-prod5.phala.network"
echo "Checking: $URL"

if curl -s "$URL" | grep -q "btn-list-objects"; then
    echo "✅ CVM is already updated to v2.0!"
else
    echo "❌ CVM is running old version"
    echo ""
    echo "To update your CVM to the new image:"
    echo ""
    echo "STEP 1: Set your API key"
    echo "------------------------"
    echo "export PHALA_CLOUD_API_KEY='your-api-key-here'"
    echo ""
    echo "STEP 2: Login to Phala"
    echo "----------------------"
    echo "phala auth login \$PHALA_CLOUD_API_KEY"
    echo ""
    echo "STEP 3: Update the CVM (try these in order)"
    echo "--------------------------------------------"
    echo "Option A: Restart to pull latest image"
    echo "phala cvms restart 0caa6fa774ccca678586fb1d142ccc627a2f96c1"
    echo ""
    echo "Option B: If that fails, try with app_ prefix"
    echo "phala cvms restart app_0caa6fa774ccca678586fb1d142ccc627a2f96c1"
    echo ""
    echo "Option C: Deploy with --uuid flag"
    echo "phala deploy --uuid 0caa6fa774ccca678586fb1d142ccc627a2f96c1 \\"
    echo "  --compose docker-compose.yml \\"
    echo "  --env-file .env"
    echo ""
    echo "MANUAL UPDATE (Easiest):"
    echo "------------------------"
    echo "1. Go to: https://dashboard.phala.network/dstack"
    echo "2. Login to your account"
    echo "3. Find your CVM (might be named 'akave-link-phala2' or similar)"
    echo "4. Click the CVM to open details"
    echo "5. Click 'Restart' or 'Redeploy'"
    echo "6. Wait 3-5 minutes for the new image to be pulled"
    echo ""
    echo "The Docker image dylanckawalec/akavelink:latest is ready and waiting!"
fi

echo ""
echo "Docker Image Info:"
echo "------------------"
echo "Repository: dylanckawalec/akavelink"
echo "Tag: latest (also tagged as v2.0)"
echo "Last Updated: $(date)"
echo ""
echo "After updating, the CVM will have:"
echo "• Upload progress bar"
echo "• List Objects button"
echo "• Clickable download links"
echo "• Cleaner UI"
